[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "python3"]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci"]

[build.nixpacksPlan.phases.build]
cmds = ["DATABASE_URL=postgresql://user:pass@localhost:5432/db npx prisma generate", "npm run build"]

[deploy]
startCommand = "npm run start -- -H 0.0.0.0"
