[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "python3"]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci"]

[build.nixpacksPlan.phases.build]
cmds = ["npx prisma generate", "npm run build"]

[deploy]
startCommand = "npm run start"
